services:
  tempus_web:
    image: ghcr.io/asam08/tempus:latest
    container_name: tempus_web
    ports:
      - "3000:3000"
    depends_on:
      - tempus_db
    environment:
      NODE_ENV: production
      POSTGRES_USER: tempus # Replace this with your user
      POSTGRES_PASSWORD: tempus # Replace this with your user password
      POSTGRES_DB: tempus
      POSTGRES_PORT: 5432
      POSTGRES_HOST: tempus_db
      BETTER_AUTH_SECRET: # Run: openssl rand -base64 32
      BETTER_AUTH_URL: # Set to your app's base URL, e.g. `http://localhost:3000`
      AUTH_ON: true # Change to false to remove auth, single user only
    restart: unless-stopped

  tempus_db:
    image: postgres:16-alpine
    container_name: tempus_db
    environment:
      POSTGRES_USER: tempus # Replace this with your user
      POSTGRES_PASSWORD: tempus # Replace this with your user password
      POSTGRES_DB: tempus
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data:
